# organization name, it's used to get github repo url, also in page title
name: cnpm

# badge style, can be "flat", "flat-square" or ""
# see http://shields.io/ for details
badge_style: flat-square

# meta headers in html
title:       cnpm
description: Private npm registry and web for Enterprise, base on MySQL and Simple Store Service.
keywords:    cnpm, npm, cnpmjs.org, private npm, Enterprise npm, mysql, s3

# list of projects, this will be sorted by name;
# every package is either string or object
projects:
 - koa-middlewares
 - cnpmjs.org
 - cnpm
 - fs-cnpm
 - qn-cnpm
 - upyun-cnpm
 - co-upyun-storage
 - upyun-storage
 - npm-user-service
 - koa-limit
 - oss-cnpm
 - sfs-client
 - sfs
 - tfs-cnpm

# list of maintainers, this won't be sorted
maintainers:
 - name:    fengmk2
   github:  fengmk2   # github account, required: we link to it
   npm:     fengmk2   # npm account, required to determine lead maintainer
   twitter: fengmk2 # twitter account, optional
   gittip:  fengmk2   # gittub badge, optional
   email:   fengmk2@gmail.com

 - name:    Yiyu He
   github:  dead-horse
   npm:     dead_horse
   twitter: deadhorse_busi
   gittip:  dead-horse
   email:   heyiyu.deadhorse@gmail.com

 - name:    Jackson Tian
   github:  JacksonTian
   npm:     jacksontian
   twitter: jacksontian
   gittip:  jacksontian
   email:   shyvo1987@gmail.com

# this determines what info will be fetched with `make db`;
# you can comment out stuff to reduce number of http requests
db.json:
  projects:
   - node        # node version, it's the lowest version from .travis.yml
   - description # package description from package.json (from npm registry)
   - maintainer  # maintainer npm account (= _npmUser of last published ver)
  maintainers:
   - packages    # amount of packages this npm user has
